### ISSUE TITLE
BUG: Science calculation bug crashed game

### ISSUE THREAD

**Issue by jsmccrumb** [jsm-boardgames/node_sevenwonders#14]
node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
at Function.values (<anonymous>)
at calculateScienceScoreFromMap (/usr/src/app/seven_wonders/models/game.js:324:30)
at Array.map (<anonymous>)
at Game.getMaxScienceWithVariableScience (/usr/src/app/seven_wonders/models/game.js:320:38)
at Game.calculateScienceScore (/usr/src/app/seven_wonders/models/game.js:340:19)
at Game.getPlayersInfo (/usr/src/app/seven_wonders/models/game.js:368:28)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Game.endRound (/usr/src/app/seven_wonders/models/game.js:477:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by jsmccrumb** [comment]
In: game-1584574777478
